# 
# Docker compose file for TANGO database and database device server
#
#
version: '2'
volumes:
  tangodb: {}
        
services:
  tangodb:
    #build:      
    #  context: ./tango-9.2.5a
    #  dockerfile: Dockerfile.db
    image: gerhardlr/tangodb:latest
    container_name: tangodb      
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
    volumes:
      - tangodb:/var/lib/mysql
    networks:
      - tango_network

  databaseds:
    #build:      
    #  context: ./tango-9.2.5a
    #  dockerfile: Dockerfile.base
    image: gerhardlr/tango_base:latest
    container_name: databaseds
    hostname: databaseds
    depends_on:
      - tangodb
    networks:
      - tango_network
    environment:
      - MYSQL_HOST=tangodb:3306 
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=databaseds:10000 
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - tangodb:3306
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/DataBaseds
      - "2"
      - -ORBendPoint
      - giop:tcp::10000
  tangotestds:
    networks:
      - tango_network
    #build:      
    #  context: ./tango-9.2.5a
    #  dockerfile: Dockerfile.base
    image: gerhardlr/tango_base:latest
    container_name: tangotestds
    hostname: tangotestds
    #depends_on:
    #  - tangodb
    environment:
      - TANGO_HOST=databaseds:10000 
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - tangodb:3306
      - --timeout=30
      - --strict
      - --
      - TangoTest test
networks:
  tango_network:
    driver: bridge
